--ЗАПОЛНЕНИЕ ТАБЛИЦЫ GENRE
MERGE INTO GENRE (GENRE_ID, NAME) KEY (GENRE_ID) VALUES (1, 'COMEDY');
MERGE INTO GENRE (GENRE_ID, NAME) KEY (GENRE_ID) VALUES (2, 'DRAMA');
MERGE INTO GENRE (GENRE_ID, NAME) KEY (GENRE_ID) VALUES (3, 'CARTOON');
MERGE INTO GENRE (GENRE_ID, NAME) KEY (GENRE_ID) VALUES (4, 'THRILLER');
MERGE INTO GENRE (GENRE_ID, NAME) KEY (GENRE_ID) VALUES (5, 'DOCUMENTARY');
MERGE INTO GENRE (GENRE_ID, NAME) KEY (GENRE_ID) VALUES (6, 'ACTION');
